{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devicefarmer.fullname" . }}-secret
  labels: {{- include "devicefarmer.labels" (dict "root" . "component" "secret") | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.value }}
  secret: {{ .Values.secret.value | b64enc | quote }}
  {{- else }}
  {{- $name := printf "%s-secret" (include "devicefarmer.fullname" .) }}
  {{- $existing := lookup "v1" "Secret" .Release.Namespace $name }}
  {{- if and $existing $existing.data.secret }}
  secret: {{ $existing.data.secret | quote }}
  {{- else }}
  secret: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
