---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - farm.example.com
  resources:
  - deviceclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - farm.example.com
  resources:
  - devicepools
  - devices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - farm.example.com
  resources:
  - devicepools/finalizers
  - devices/finalizers
  verbs:
  - update
- apiGroups:
  - farm.example.com
  resources:
  - devicepools/status
  - devices/status
  verbs:
  - get
  - patch
  - update
